import { describe, expect, test } from "vite-plus/test";
import { defaults, defineParams, type Infer, num, pick, toggle } from "./index.ts";

// Full deck-box schema (every param in parametric-mtg-deck-box/src/params.ts).
const deckSchema = defineParams({
  cardCount: num({ def: 100, min: 10, max: 250, step: 1, group: "cards", label: "Card count" }),
  extraCards: num({
    def: 10,
    min: 0,
    max: 40,
    step: 1,
    group: "cards",
    label: "Token headroom (cards)",
  }),
  cardWidth: num({
    def: 66.5,
    min: 60,
    max: 72,
    step: 0.1,
    group: "cards",
    label: "Card width (sleeved)",
  }),
  cardHeight: num({
    def: 92,
    min: 85,
    max: 97,
    step: 0.1,
    group: "cards",
    label: "Card height (sleeved)",
  }),
  cardThickness: num({
    def: 0.6,
    min: 0.25,
    max: 1.2,
    step: 0.005,
    group: "cards",
    label: "Thickness per card",
  }),
  sideClearance: num({
    def: 0.8,
    min: 0,
    max: 3,
    step: 0.1,
    group: "fit",
    label: "Side clearance",
  }),
  stackClearance: num({
    def: 3,
    min: 0,
    max: 10,
    step: 0.5,
    group: "fit",
    label: "Stack clearance",
  }),
  headroom: num({ def: 1, min: 0, max: 5, step: 0.5, group: "fit", label: "Headroom" }),
  wall: num({ def: 3, min: 2, max: 4.4, step: 0.2, group: "shell", label: "Wall thickness" }),
  floor: num({ def: 2.4, min: 1.2, max: 4, step: 0.2, group: "shell", label: "Floor thickness" }),
  cornerRadius: num({ def: 3, min: 0, max: 8, step: 0.5, group: "shell", label: "Corner radius" }),
  bodyStyle: pick(["solid", "window", "slots", "hex"] as const, {
    def: "solid",
    group: "shell",
    label: "Body style",
    optionLabels: { solid: "Solid", window: "Window", slots: "Slots", hex: "Honeycomb" },
  }),
  openingScale: num({
    def: 0.65,
    min: 0.35,
    max: 0.9,
    step: 0.05,
    group: "opening",
    label: "Opening size",
  }),
  lidStyle: pick(["friction", "snap", "magnet"] as const, {
    def: "friction",
    group: "lid",
    label: "Closure",
    optionLabels: { friction: "Friction fit", snap: "Snap fit", magnet: "Magnets" },
  }),
  lipHeight: num({ def: 13, min: 6, max: 25, step: 0.5, group: "lid", label: "Lip height" }),
  lipWall: num({ def: 1.4, min: 0.8, max: 2.4, step: 0.1, group: "lid", label: "Lip wall" }),
  lidFit: num({
    def: 0.25,
    min: 0.05,
    max: 0.5,
    step: 0.05,
    group: "lid",
    label: "Lid fit clearance",
  }),
  lidTop: num({ def: 2.4, min: 1.2, max: 4, step: 0.2, group: "lid", label: "Lid top thickness" }),
  snapBump: num({
    def: 0.3,
    min: 0.1,
    max: 0.6,
    step: 0.05,
    group: "snap",
    label: "Snap engagement",
  }),
  magnetDiameter: num({
    def: 3,
    min: 2,
    max: 6,
    step: 0.5,
    group: "magnet",
    label: "Magnet diameter",
  }),
  magnetHeight: num({ def: 2, min: 1, max: 4, step: 0.5, group: "magnet", label: "Magnet height" }),
  notchWidth: num({
    def: 20,
    min: 0,
    max: 40,
    step: 1,
    group: "notch",
    label: "Notch width (0 = off)",
  }),
  notchDepth: num({
    def: 11,
    min: 4,
    max: 25,
    step: 0.5,
    group: "notch",
    label: "Notch depth",
    maxKey: "lipHeight",
  }),
  recessWidth: num({
    def: 0,
    min: 0,
    max: 30,
    step: 1,
    group: "notch",
    label: "Side recesses (0 = off)",
  }),
  pushHoleD: num({
    def: 0,
    min: 0,
    max: 30,
    step: 1,
    group: "notch",
    label: "Push-up hole Ø (0 = off)",
  }),
});

// Full a4-trays schema (every param in a4-stackable-trays/src/params.ts).
const traySchema = defineParams({
  itemWidth: num({ def: 210, min: 40, max: 400, step: 1, group: "size", label: "Item width" }),
  itemLength: num({ def: 297, min: 40, max: 400, step: 1, group: "size", label: "Item length" }),
  clearance: num({ def: 10, min: 0, max: 20, step: 0.5, group: "size", label: "Clearance" }),
  frontOverhang: num({
    def: 0,
    min: 0,
    max: 400,
    step: 1,
    group: "size",
    label: "Front overhang (0 = enclosed)",
    maxKey: "itemLength",
  }),
  frontLip: num({
    def: 0,
    min: 0,
    max: 90,
    step: 1,
    group: "size",
    label: "Front lip (0 = open top)",
    maxKey: "depth",
  }),
  scoop: num({ def: 0, min: 0, max: 120, step: 2, group: "size", label: "Front scoop (0 = off)" }),
  scoopDepth: num({
    def: 30,
    min: 0,
    max: 100,
    step: 1,
    group: "size",
    label: "Scoop depth (0 = off)",
  }),
  depth: num({ def: 45, min: 15, max: 90, step: 1, group: "wall", label: "Wall height" }),
  wall: num({ def: 2.4, min: 1.6, max: 4, step: 0.2, group: "wall", label: "Wall thickness" }),
  cornerRadius: num({ def: 8, min: 0, max: 20, step: 0.5, group: "wall", label: "Corner radius" }),
  wallStyle: pick(
    ["solid", "louvres", "grid", "holes", "diamond", "honeycomb", "voronoi"] as const,
    {
      def: "louvres",
      group: "wall",
      label: "Wall style",
    },
  ),
  wallPatternScale: num({
    def: 9,
    min: 5,
    max: 16,
    step: 0.5,
    group: "wallPat",
    label: "Pattern size",
  }),
  wallPatternMargin: num({
    def: 7,
    min: 2,
    max: 20,
    step: 0.5,
    group: "wallPat",
    label: "Pattern margin",
  }),
  floor: num({ def: 3.0, min: 1.6, max: 4, step: 0.2, group: "floor", label: "Floor thickness" }),
  floorStyle: pick(
    ["solid", "louvres", "grid", "holes", "diamond", "honeycomb", "voronoi"] as const,
    {
      def: "solid",
      group: "floor",
      label: "Floor style",
    },
  ),
  floorPatternScale: num({
    def: 9,
    min: 5,
    max: 16,
    step: 0.5,
    group: "floorPat",
    label: "Pattern size",
  }),
  floorPatternMargin: num({
    def: 7,
    min: 2,
    max: 20,
    step: 0.5,
    group: "floorPat",
    label: "Pattern margin",
  }),
  ridgeHeight: num({
    def: 1.6,
    min: 0.6,
    max: 2.2,
    step: 0.1,
    group: "stack",
    label: "Ridge height",
  }),
  ridgeWidth: num({ def: 1.2, min: 0.8, max: 3, step: 0.1, group: "stack", label: "Ridge width" }),
  stackRidge: toggle({ def: true, group: "stack", label: "Stacking ridge" }),
  labelRail: pick(["none", "left", "right", "both"] as const, {
    def: "none",
    group: "label",
    label: "Label rail",
    optionLabels: { none: "None", left: "Left", right: "Right", both: "Both" },
  }),
});

describe("acceptance: every source param is expressible", () => {
  test("deck-box defaults reproduce exactly", () => {
    const expected: Infer<typeof deckSchema> = {
      cardCount: 100,
      extraCards: 10,
      cardWidth: 66.5,
      cardHeight: 92,
      cardThickness: 0.6,
      sideClearance: 0.8,
      stackClearance: 3,
      headroom: 1,
      wall: 3,
      floor: 2.4,
      cornerRadius: 3,
      lipHeight: 13,
      lipWall: 1.4,
      lidFit: 0.25,
      lidTop: 2.4,
      notchWidth: 20,
      notchDepth: 11,
      lidStyle: "friction",
      snapBump: 0.3,
      magnetDiameter: 3,
      magnetHeight: 2,
      bodyStyle: "solid",
      openingScale: 0.65,
      recessWidth: 0,
      pushHoleD: 0,
    };
    expect(defaults(deckSchema)).toEqual(expected);
  });

  test("a4-trays defaults reproduce exactly", () => {
    const expected: Infer<typeof traySchema> = {
      itemWidth: 210,
      itemLength: 297,
      clearance: 10,
      frontOverhang: 0,
      wall: 2.4,
      floor: 3.0,
      depth: 45,
      frontLip: 0,
      scoop: 0,
      scoopDepth: 30,
      cornerRadius: 8,
      ridgeHeight: 1.6,
      ridgeWidth: 1.2,
      wallStyle: "louvres",
      wallPatternScale: 9,
      wallPatternMargin: 7,
      floorStyle: "solid",
      floorPatternScale: 9,
      floorPatternMargin: 7,
      stackRidge: true,
      labelRail: "none",
    };
    expect(defaults(traySchema)).toEqual(expected);
  });
});
